name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: Build
#       run: swift build -v
#     - name: Run tests
#       run: swift test -v

    steps:
#     - name: Select latest Xcode
#       run: "sudo xcode-select -s /Applications/Xcode_$XC_VERSION.app"
    - uses: actions/checkout@v2
    
#     - name: Build
#       run: swift build -v
      
#     - name: Run tests
#       run: swift test -v 


    - name: Run Unit and UI Tests
      run: xcodebuild test -workspace GithubActionDemo.xcodeproj/project.xcworkspace
          -scheme GithubActionDemo -destination 'platform=iOS Simulator,name=iPhone 11
          Pro Max'
    - name: Test
      run: xcodebuild test -project Proj.xcodeproj -scheme ProjTests -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11,OS=15"
